/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bsma;

import java.awt.Color;
import java.awt.Container;
import java.awt.Font;
import java.awt.Graphics;
import java.util.ArrayList;
import java.util.Observable;
import java.util.Observer;

/**
 *
 * @author g_ric_000
 */
public class BSMAGui extends javax.swing.JFrame implements Observer {

    private ArrayList<Node> memoryChunks;
    private static final int VISUAL_MEMORY_WIDTH = 150; //how wide in pixels the memory will be 
    private static final int VISUAL_MEMORY_SCALE = 2;
    private static final int WINDOW_WIDTH = 600;
    private static final int WINDOW_HEIGHT = 600;
    private static final int START_X = 225;
    private static final int START_Y = 100;
    
    /**
     * Creates new form BSMAGui
     */
    public BSMAGui() {
        initComponents();
        getContentPane().setBackground(Color.white);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BSMAGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BSMAGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BSMAGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BSMAGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new BSMAGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public void paint(Graphics g) {
        super.paint(g);
        
        //I have no friggin idea why this won't work
        Font font;
        g.setColor(Color.BLACK);
        font = new Font(Font.SANS_SERIF, Font.BOLD, 45);
        g.setFont(font);
        g.drawString("Binary Buddy Memory Management System!", 200, 35);
        
        int x = START_X;
        int y = START_Y;
        for (Node memoryChunk : memoryChunks) {
            if(memoryChunk.isEmpty()) {
                g.setColor(Color.GRAY);
            } else {
                g.setColor(Color.RED);
            }
            g.fill3DRect(x, y, VISUAL_MEMORY_WIDTH, memoryChunk.getSize() * VISUAL_MEMORY_SCALE, true);
            y += memoryChunk.getSize() * VISUAL_MEMORY_SCALE;
        }
    }

    @Override
    public void update(Observable observed, Object data) {
            memoryChunks = (ArrayList<Node>) data;
            repaint();
    }
}
